export { default as HomeLayout } from "./HomeLayout"
export { default as Login } from "./Login"
export { default as Landing } from "./Landing"
export { default as Register} from "./Register"
export { default as Gestor } from "./Gestor"
export { default as Additional} from "./AdditionalPage"