export { default as Login } from "./Login"
export { default as Landing } from "./Landing"
export { default as Register} from "./Register"
export { default as Additional} from "./AdditionalPage"
export { default as Productos } from "./Productos"
export { default as Pedidos } from "./Pedidos"
export { default as Clientes } from "./Clientes"
export { default as Profile } from "./Profile"
export { default as Envios } from "./Envios"
export { default as Pagos } from "./Pagos"
export { default as Contacto } from "./Contacto"
export { default as Estadisticas } from "./Estadisticas"
export { default as Settings } from "./Settings"
export { default as Crear } from "./Crear"